### PR TITLE
feat: import new individual learner report dashboard

### PR DESCRIPTION
**Pull request by Ian2012**
### Description

This PR imports the new charts for the individual learner report dashboard. It also moves the engagement datasets from Aspects to DBT.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by bmtcril** [comment]
@Ian2012 @SoryRawyer the changes here conflict with #765 in that some of the Superset queries it uses are being moved to dbt as part of these changes. I know that the reason we were using the template queries instead of dbt for some of these was to work around ClickHouse and perform filtering on rows in CTEs. I'm not sure if that's still required or being used in these particular queries, but we should make a decision about whether to move these to dbt or not before either of these merges.

**Comment by SoryRawyer** [comment]
Sorry for the delay @bmtcril @Ian2012. My understanding is that we couldn't make use of ClickHouse indexes if we pushed these queries into views with dbt, but that doesn't seem to be the case anymore. I tried running a few queries with `settings force_primary_key=1` and the queries ran successfully (they would've thrown an error if no primary key was used). I think that means we can safely move these queries under dbt's purview.

**Comment by Ian2012** [comment]
@SoryRawyer thanks for your performance review. I'm closing this PR to reduce the amount of code changes:
The first one: https://github.com/openedx/tutor-contrib-aspects/pull/785 will change the naming from using whitespace and `/` in the column names and migrate the `fact_*_engagement` datasets to DBT.

The second one will import the individual learner dashboard

**Comment by openedx-webhooks** [comment]
@Ian2012 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/778&entry.1484655318=https://github.com/Ian2012&entry.752974735=2024-05-07+22:12&entry.1917517419=2024-05-08+20:10&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
