### PR TITLE
Update ClickHouse host port configuration

### PR DESCRIPTION
**Pull request by bmtcril**
The default host port conflicts with MinIO, this changes the default port and makes the host ports match the configured internal ports like we do for Supserset.

Closes: #348

### CODE REVIEW

**Comment by bmtcril** [comment]
FWIW: I fully expect this to uncover bugs where that port is hard coded elsewhere, but it's best to find them now!

**Comment by bmtcril** [comment]
This did uncover a bunch of small things, I've updated the port config names to reflect what they actually are (a number of native ports were named http) and successdfully tested locally in tutor local and dev with minio. I have not tested k8s, but I'm hoping CI will flush out any issues.

**Comment by Ian2012** [comment]
@bmtcril can you perform a little test in Clickhouse cloud?

**Comment by bmtcril** [comment]
Checked against CH Cloud, seems good. I think there's an unrelated (?) error publishing courses to CH Cloud from event-sink-clickhouse, though.

**Comment by bmtcril** [comment]
I found and fixed the event sink error, it was unrelated but right on a line I touched earlier. 👎

**Review by Ian2012 — APPROVED** [review]

**Pull request merged**
