### PR TITLE
fix: revert value for ClickHouse HTTP settings (FC-0033)

### PR DESCRIPTION
**Pull request by SoryRawyer**
ClickHouse version 23.6 featured a [backwards-incompatible change](https://clickhouse.com/docs/en/whats-new/changelog#backward-incompatible-change-2) that broke some of our existing tooling. This PR uses the old default value and provides a way to override other settings that need to be configured at the user level (previously we only needed to override global settings).

I tried to follow the existing pattern for global config settings, but please let me know if I've missed anything, either in the patches or elsewhere.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — APPROVED** [review]
💯

**Comment by bmtcril** [comment]
Hmm, looks like maybe it has to have a unique filename for k8s? @Ian2012 do you know what needs to be changed?

**Comment by SoryRawyer** [comment]
Interesting. I don't think the name matters from ClickHouse's perspective so I renamed the config. I confirmed it continued to set the value locally, so hopefully k8s is happy with the new name.

**Review by Ian2012 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@SoryRawyer 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/382&entry.1484655318=https://github.com/SoryRawyer&entry.752974735=2023-09-13+16:15&entry.1917517419=2023-09-13+18:22&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
