### PR TITLE
refactor: use extended block names in instructor dashboard (FC-0033)

### PR DESCRIPTION
**Pull request by SoryRawyer**
This change updates Superset assets to use the new dbt models that include block display names with location information. This includes the video and problem filters as well as the values returned by course-level charts. The screenshots below show an example of the new format.

Using new display names in charts:
Screenshot from 2023-10-17 14-45-05

Using new display names in filters:
Screenshot from 2023-10-17 14-45-19

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — APPROVED** [review]
🎉

**Comment by bmtcril** [comment]
@Ian2012 this is what we came to as a solution in the demo, the instructor was confused by the ordering of blocks and wanted them in the order that they appear in the course. Similarly they didn't always know the names of blocks (or had the same name for numerous blocks) and wanted to be able to identify it in the course. So I think this solves for both of those things. I'd like to get it into the beta and gather more feedback there.

**Comment by openedx-webhooks** [comment]
@SoryRawyer 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/476&entry.1484655318=https://github.com/SoryRawyer&entry.752974735=2023-10-17+18:50&entry.1917517419=2023-10-18+14:39&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
