### PR TITLE
feat: allow to install extra dbt packages

### PR DESCRIPTION
**Pull request by Ian2012**
## Description

This PR allows installing custom DBT packages

Author concerns:
- Most DBT packages require configuration and changes in the project itself, do not see any reason to add this feature.
- If you want to add a package, fork the repo and modify the project as you need.
- This approach cannot override already existing packages in packages.yml
- Some DBT packages depend on already installed DBT packages, this creates a conflict
- It would be better to override completely the DBT packages file. Waiting for feedback

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by bmtcril** [comment]
I think letting people create their own packages (or having officially supported packages for things like "small class on-campus" use cases without having to fork is useful. I agree it's probably best to just let people override the whole file, it will be on them to make sure the necessary base packages are installed. I also agree that being able to override the `dbt_project.yml` is going to be necessary, so hopefully we can do both the same way.

**Review by bmtcril — APPROVED** [review]
LGTM, thanks!

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/138&entry.1484655318=https://github.com/Ian2012&entry.752974735=2023-07-05+14:42&entry.1917517419=2023-07-05+16:45&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
