### PR TITLE
feat: add dataset for pageview engagement charts (FC-0051)

### PR DESCRIPTION
**Pull request by SoryRawyer**
This PR adds a dataset that can be used to show the number of learners who have:
1. viewed at least one page in a section or subsection
2. viewed all pages in a section or subsection

This is still a draft because I wanted to give a more elaborate example of how I imagined using the models added in [my recent aspects-dbt PR](https://github.com/openedx/aspects-dbt/pull/52).

Here is a chart that I made from this dataset:
Screenshot from 2024-03-19 14-03-59

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by bmtcril** [comment]
@SoryRawyer I haven't had a chance to review yet, but I think the CI errors can be fixed with a rebase

**Comment by SoryRawyer** [comment]
@bmtcril I don't think I'm missing any commits from `main`. Do you have any ideas what else might be causing the Docker hub login step to fail?

**Comment by Ian2012** [comment]
@SoryRawyer can you add this chart to the Instructor Dashboard too?

**Comment by bmtcril** [comment]
I think this is failing due to secrets not being available since you don't have write on the repo. I suspect this will happen with forks, too. We can merge with these failures, but if we don't 100% need those images to build we might want to just skip those when they can't run (if that's even possible)?

**Review by bmtcril — APPROVED** [review]
I think this just needs another rebase to get the latest changes to the build-image workflow and it should be good to go!

**Comment by openedx-webhooks** [comment]
@SoryRawyer 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/673&entry.1484655318=https://github.com/SoryRawyer&entry.752974735=2024-03-19+19:53&entry.1917517419=2024-03-25+14:28&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
