### PR TITLE
feat: replace double quotes in problem responses (FC-0033)

### LINKED ISSUE #494: Bug: Distribution of Responses errors
Certain questions on the Beta server are throwing an error for the Distribution of Responses chart:

```
:HTTPDriver for http://clickhouse:8123 returned response code 400)
 Code: 26. DB::ParsingException: Cannot parse quoted string: expected opening quote ''', got '"': while executing 'FUNCTION if(startsWith(responses, '[') :: 4, CAST(responses, 'Array(String)') :: 1, array(responses) :: 3) -> if(startsWith(re
This may be triggered by: 
Issue 1002 - The database returned an unexpected error.
```

This appears to be related to the parsing of multiple answers in fact_problem_responses.sql: https://github.com/openedx/tutor-contrib-aspects/blob/4ea65d69307b53e5da96cedb46296c785fe3a259/tutoraspects/templates/openedx-assets/queries/fact_problem_responses.sql#L19

Seems to be because the answers are sometimes single quoted, sometimes double quoted:

```
 ["Un emprunt à l'anglais ou anglicisme", 'Un type de demande', 'Une question structurée et précise']                                                                
 ['Un type de demande']                                                                                                                                              │
 ['Une question structurée et précise', 'Un type de poisson']
```

### PR DESCRIPTION
**Pull request by SoryRawyer**
Fixes #494 by escaping single quotes and replacing double quotes with single quotes in problem responses. This allows problem responses to be successfully parsed as arrays. Below is a screenshot of answers with single quotes being displayed in the problem performance tab:

Screenshot from 2023-10-26 11-23-09

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @SoryRawyer!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — APPROVED** [review]
Awesome, thank you!

**Review by Ian2012 — APPROVED** [review]
Altough this is working, is this the right place to do this change?

Can we update event-routing-backends to do not send the data like that?

**Comment by openedx-webhooks** [comment]
@SoryRawyer 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/498&entry.1484655318=https://github.com/SoryRawyer&entry.752974735=2023-10-26+15:25&entry.1917517419=2023-10-26+17:01&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by bmtcril** [comment]
@Ian2012 I think we want to capture the original values as stored in the LMS as much as possible at the top level, even if they're invalid JSON. That way if this workaround fails in some way we won't need to replay all of the data, we can just update the impacted MVs / tables in Aspects.

**Pull request merged**
