### PR TITLE
feat: restore mysql database source

### PR DESCRIPTION
**Pull request by Ian2012**
Restores the MySQL connection with a new read-only user that can be used by operators to create new reports

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — CHANGES_REQUESTED** [review]
I would really prefer to not have this connection by default due to performance and security considerations. If there are reports that need information from mysql we should talk about other ways of getting it, or perhaps it can be in an optional plugin.

**Comment by Ian2012** [comment]
What if we hide it in a setting `ASPECTS_ENABLE_MYSQL_CONNECTION` disabled by default?

**Comment by Ian2012** [comment]
The information for the following reports is not in Clickhouse:

- Total unique users
- Course approval rate (approved users / total users)

The first one is hard to make for the whole platform as there can be very old users and it's not suitable to perform a big backfill for this data. Or we can create a sink for user profiles and user anon id to be able to join user information

For the second one, I'm not so sure if there is a course approval xAPI event

**Comment by openedx-webhooks** [comment]
@Ian2012 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/283&entry.1484655318=https://github.com/Ian2012&entry.752974735=2023-08-04+21:06&entry.1917517419=2023-08-14+20:30&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
