### PR TITLE
feat: move page engagement to an mv

### PR DESCRIPTION
**Pull request by Ian2012**
### Description

This PR moves the the page engagement to an MV and update the datasets to apply filters on the CTEs.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — COMMENTED** [review]
This mostly seems good, though I'm am seeing some performance regressions on the at-risk engagement charts (basically all of them). Things that I believed were working before are now timing out (Video Views per Section/Subsection (at-risk)) or OOM (Problem interactions (at-risk)). Any idea why those would be impacted?

**Comment by Ian2012** [comment]
I considered migrating the at-risk dataset to a dictionary similar to the PII dataset. Not sure if there is any relation with my changes, unless there is a change on the other two PRs that broke this:

- #826 
- #825

**Comment by bmtcril** [comment]
Yeah I checked those and didn't see anything obvious, we should probably not block on that and try to fix forward once everything is updated.

**Review by bmtcril — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/833&entry.1484655318=https://github.com/Ian2012&entry.752974735=2024-05-27+17:38&entry.1917517419=2024-05-28+16:54&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
