### PR TITLE
fix: Environment variable contain whitespace issue

### PR DESCRIPTION
**Pull request by Yagnesh1998**
**Description:**

after installing aspect as https://github.com/openedx/tutor-contrib-aspects#readme official docs. facing this issue when I hit enter tutor local do init in an olive release as well in the palm.

`ERROR: environment variable name 'RALPH_SENTRY_DSN ' may not contain whitespace.` Some other variables have this issue of whitespace. here this error also.

-  environment variable name 'RALPH_EXECUTION_ENVIRONMENT ' may not contain whitespace.
-  environment variable name 'RALPH_SENTRY_CLI_TRACES_SAMPLE_RATE ' may not contain whitespace.
-  environment variable name 'RALPH_SENTRY_LRS_TRACES_SAMPLE_RATE ' may not contain whitespace.
-  environment variable name 'RALPH_SENTRY_IGNORE_HEALTH_CHECKS ' may not contain whitespace.

and this issue comes from `**tutor-contrib-aspects/tutoraspects/templates/aspects/apps/ralph/config/env**` in this file.

so this pull request's purpose is to fix this issue of white space after removing this working fine.

**Supporting information:**

**Docker version 24.0.5
Docker Compose version v2.6.1**
**tutor version: v15.3.5(Olive) & v16.0.2 (Palm) check this issue**

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Yagnesh1998!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by itsjeyd** [comment]
Hi @Yagnesh1998! Thank you for this contribution. It looks like the changes are ready for review, so I'm lining them up for a test run.

CC @Ian2012 @bmtcril

**Review by Ian2012 — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Yagnesh1998 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/301&entry.1484655318=https://github.com/Yagnesh1998&entry.752974735=2023-08-16+09:44&entry.1917517419=2023-08-16+13:32&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by Ian2012** [comment]
@Yagnesh1998 thanks for your contribution

**Comment by Yagnesh1998** [comment]
@Ian2012 it's my pleasure.

**Pull request merged**
