### PR TITLE
fix: override pre-generated database connection

### PR DESCRIPTION
**Pull request by Ian2012**
### Description

It was supposed that the connection string from ClickHouse and MySQL were fixed by this PR: https://github.com/openedx/tutor-contrib-aspects/pull/581. However, the asset generated with a random user/password were used instead. This PR makes sure that the SQL alchemy string is correct.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by bmtcril** [comment]
What is the best way to test this? Is there any concern about bootstrapping a new instance with these changes?

**Comment by Ian2012** [comment]
No, there isn't any concern on new instances. Already installed instances should be repaired.

You can test on a fresh local installation, and verify the connection string is using your current credentials instead of the ones on the CI of this repository

**Comment by bmtcril** [comment]
I've never run into the bug locally, though, is this only showing up in k8s?

**Review by bmtcril — APPROVED** [review]
I'm still not sure how it was broken initially, but I can confirm that this change didn't break anything for me locally.

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/863&entry.1484655318=https://github.com/Ian2012&entry.752974735=2024-06-17+17:07&entry.1917517419=2024-06-17+20:56&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
