### PR TITLE
feat: Auto delete old charts

### LINKED ISSUE #370: Feat: Delete known-orphaned Superset assets
Right now if we re-export a dashboard and an old chart is no longer on it, that chart will live forever in a live system unless the operator manually deletes it. I think we can have a way to remove known-orphaned charts or dashboards by having a file that tracks all IDs that have been released and then subsequently orphaned. I think we'd have to maintain this manually, but it's easy to add ids that have been missed.

I'm thinking a yaml file that just stores a dict of types (dashboard, chart, etc) and a small script that loops through them and calls the API to delete them, similar to how we do import. It can eat errors if the id already doesn't exist.

### PR DESCRIPTION
**Pull request by saraburns1**
Closes #370 

Output when importing zips
Screenshot 2024-09-13 at 10 47 38 AM
Screenshot 2024-09-13 at 10 47 53 AM

### CODE REVIEW

**Comment by bmtcril** [comment]
Nice, I'm glad you're tackling this! Once concern that I tried to raise in the original ticket is that we can't assume that any assets in Superset that aren't current Aspects assets should be deleted (like custom charts and dashboards) so we need some kind of way to say "this asset uuid is a deleted Aspects asset from the past that should be cleaned up".

**Comment by saraburns1** [comment]
> Nice, I'm glad you're tackling this! Once concern that I tried to raise in the original ticket is that we can't assume that any assets in Superset that aren't current Aspects assets should be deleted (like custom charts and dashboards) so we need some kind of way to say "this asset uuid is a deleted Aspects asset from the past that should be cleaned up".

could we instead have a file that keeps a list of unused assets that we DONT want to delete? that might be easier to maintain than a list of ones TO delete

**Comment by bmtcril** [comment]
I don't think we have a way of knowing which custom assets someone added are unused / deletable. We can only know our own assets, so we could put a check in CI or something that would fail a build if there were unused assets left in our changes. Then we could add them to the list. Seems kind of error prone, but if we put the reminder to add them to the list in the error message it might help?

**Comment by saraburns1** [comment]
Ahhh makes sense. Cool, I'll do that

**Pull request closed without merging**
